version: '3.9'

services:
 postgres:
    container_name: fpcomm_pgdb
    restart: unless-stopped
    image: postgres:15
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2g
        reservations:
          memory: 512m
    volumes:
      - fpcomm_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  fpcomm_postgres_data: